rails-real-ru/acl/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'
  get 'signup', to: 'users#new'

  resource :session, only: %i[new create destroy]

  resources :users
  resources :posts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

rails-real-ru/acl/app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  validates :title, presence: true
  validates :body, length: { maximum: 500 }

  belongs_to :author, class_name: 'User'
end

rails-real-ru/acl/app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_secure_password

  validates :name, presence: true
  validates :email, presence: true
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  has_many :posts, foreign_key: 'author_id', dependent: :destroy
end

rails-real-ru/acl/app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include AuthConcern
  include Pundit::Authorization
end

rails-real-ru/acl/app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]

  after_action :verify_authorized, except: %i[index show]

  # BEGIN
  def index
    @posts = Post.all
    authorize @posts
  end

  def show; end

  def new
    authorize Post
    @post = Post.new
  end

  def create
    authorize Post
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to @post, notice: t('.success')
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: t('.success')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post.destroy

    redirect_to posts_path, notice: t('.success')
  end

  private

  def set_post
    @post = Post.find(params[:id])
    authorize @post
  end

  def post_params
    params.require(:post).permit(:title, :body)
  end
  # END
end

rails-real-ru/acl/app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find params[:id]

    @posts = @user.posts
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find params[:id]
  end

  def create
    @user = User.new(user_params)

    if @user.save
      sign_in @user
      redirect_to @user, notice: 'User was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @user = User.find params[:id]

    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @user = User.find params[:id]

    @user.destroy

    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(
      :name,
      :email,
      :password,
      :password_confirmation
    )
  end
end

rails-real-ru/acl/app/views/users/edit.html.slim
= content_for :title do
  = 'Editing user'

== render 'form', user: @user

hr

.d-flex
  = link_to t('show'), @user, class: 'btn btn-outline-primary me-2'
  = link_to t('back'), :back, class: 'btn btn-outline-primary'

rails-real-ru/acl/app/views/users/index.html.slim
= content_for :title do
  = t('.users')

table.table.table-striped.table-hover.mb-5
  thead
    tr
      th{ scope = 'col' } #
      th{ scope = 'col' } Name
      th

  tbody
    - @users.each_with_index do |user, i|
      tr
        th{ scope = 'row' } = i + 1
        td = user.name
        td.d-flex
          = link_to t('show'), user, class: 'me-4 '
          = link_to t('edit'), edit_user_path(user), class: 'me-4 '
          = link_to t('destroy'), user, data: { confirm: t('destroy_confirmation') }, method: :delete, class: 'link-danger'

= link_to t('.new_user'), new_user_path, class: 'btn btn-primary'

rails-real-ru/acl/app/views/users/new.html.slim
= content_for :title do
  = 'New user'

== render 'form', user: @user

hr

= link_to t('back'), :back, class: 'btn btn-outline-primary'

rails-real-ru/acl/app/views/users/show.html.slim
= content_for :title do
  = @user.name

p
  strong.me-2 = t('.email')
  = @user.email

p
  strong.me-2 = t('.is_admin')
  = @user.admin?

- if @posts.any?
  h4 = t('.posts')

  table.table.table-striped.table-hover.mb-5
    thead
      tr
        th{ scope = 'col' } #
        th{ scope = 'col' } Name

    tbody
      - @posts.each_with_index do |post, i|
        tr
          th{ scope = 'row' } = i + 1
          td = link_to post.title, post

hr

.d-flex
  = link_to t('edit'), edit_user_path(@user), class: 'btn btn-outline-primary me-2'
  = link_to t('back'), :back, class: 'btn btn-outline-primary'