rails-real-ru/system-tests/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'homes#index'

  resources :posts do
    scope module: :posts do
      resources :comments, only: %i[edit create update destroy]
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

rails-real-ru/system-tests/app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :body, length: { maximum: 500 }
end

rails-real-ru/system-tests/app/models/post/comment.rb
# frozen_string_literal: true

class Post
  class Comment < ApplicationRecord
    belongs_to :post

    validates :body, presence: true
  end
end

rails-real-ru/system-tests/app/controllers/homes_controller.rb
# frozen_string_literal: true

class HomesController < ApplicationController
  def index; end
end

rails-real-ru/system-tests/app/controllers/posts/comments_controller.rb
# frozen_string_literal: true

module Posts
  class CommentsController < ApplicationController
    before_action :set_post

    def edit
      @comment = Post::Comment.find(params[:id])
    end

    def create
      @comment = @post.comments.build(comment_params)

      if @comment.save
        redirect_to @post, notice: 'Comment was successfully created.'
      else
        redirect_to @post, alert: 'Comment has not been added'
      end
    end

    def update
      @comment = Post::Comment.find(params[:id])

      if @comment.update(comment_params)
        redirect_to @post, notice: 'Comment was successfully updated.'
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @comment = Post::Comment.find(params[:id])
      @comment.destroy

      redirect_to @post
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:post_id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:post_comment).permit(:body)
    end
  end
end

rails-real-ru/system-tests/app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  def index
    @posts = Post.order(created_at: :desc).all
  end

  def show
    @post = Post.find params[:id]
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find params[:id]
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post, notice: 'Post was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @post = Post.find params[:id]

    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post = Post.find params[:id]

    @post.destroy

    redirect_to posts_url, notice: 'Post was successfully destroyed.'
  end

  private

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:title, :body)
  end
end

rails-real-ru/system-tests/app/views/layouts/application.html.slim
doctype html
html.h-100
  head
    title System tests
    == csrf_meta_tags
    == csp_meta_tag
    meta name="keywords" content="template language"
    meta name="author" content='author'
    meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"
    = stylesheet_pack_tag 'application', media: 'all'
    = javascript_pack_tag 'application'

  body.d-flex.flex-column.h-100

    = render 'layouts/shared/nav'

    = render 'layouts/shared/flash'

    main
      .mt-4.mb-5.pb-5
        .container
          .p-4.align-items-center.border.shadow.bg-white.rounded-3
            .mb-4
              h1.h2 = yield :title

            == yield

    footer.bg-dark.text-light.mt-auto
      .container-xl
        .row.py-2
          = "© Hexlet ltd, #{Time.current.year}"

rails-real-ru/system-tests/app/views/posts/_form.html.slim
= simple_form_for(post) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  = f.input :title
  = f.input :body

  = f.button :submit, class: 'btn btn-success mt-4 btn-block'

rails-real-ru/system-tests/app/views/posts/index.html.slim
= content_for :title do
  = 'Posts'

table.table.table-striped.table-hover.mb-5
  thead
    tr
      th{ scope = 'col' } #
      th{ scope = 'col' } Title
      th

  tbody
    - @posts.each_with_index do |post, i|
      tr
        th{ scope = 'row' } = i + 1
        td = post.title
        td.d-flex
          .me-4 = link_to 'Show', post
          .me-4 = link_to 'Edit', edit_post_path(post)
          = link_to 'Destroy', post, data: { confirm: 'Are you sure?' }, method: :delete, class: 'link-danger'

= link_to 'New Post', new_post_path, class: 'btn btn-primary'

rails-real-ru/system-tests/app/views/posts/show.html.slim
= content_for :title do
  = @post.title
p
  strong.me-2 Body:
  = @post.body
.mt-3
  - if @post.comments.any?
    h3 Comments

    - @post.comments.each do |comment|
      .card.mb-2.p-3
        .d-flex.justify-content-between.align-items-center
          .col-10
            small.font-weight-bold
              == comment.body
          .col-2
            small.me-2
              = l(comment.created_at, format: :short)

            = link_to 'Edit', edit_post_comment_path(@post, comment), class: 'me-2'

            = link_to post_comment_path(@post, comment), method: :delete, data: { confirm: 'Are you sure?' } do
              = 'Delete'
  .my-2

  = simple_form_for @post.comments.build, url: post_comments_path(@post) do |f|
    = f.input :body, label: false, as: :text
    = f.submit class: 'btn btn-primary'
hr

.d-flex
  = link_to 'Edit', edit_post_path(@post), class: 'btn btn-outline-primary me-2'
  = link_to 'Back', :back, class: 'btn btn-outline-primary'