rails-full-ru/caching/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope module: :web do
    root 'home#index'

    resources :articles
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

rails-full-ru/caching/app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rails-full-ru/caching/app/models/article.rb
# frozen_string_literal: true

class Article < ApplicationRecord
  # BEGIN
  def last_reading_date
    Rails.cache.fetch("#{cache_key_with_version}/last_reading_date", expires_in: 12.hours) do
      Time.current
    end
  end
  # END
end

rails-full-ru/caching/app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

rails-full-ru/caching/app/controllers/web/application_controller.rb
# frozen_string_literal: true

class Web::ApplicationController < ApplicationController
end

rails-full-ru/caching/app/controllers/web/articles_controller.rb
# frozen_string_literal: true

class Web::ArticlesController < Web::ApplicationController
  # BEGIN
  caches_action :show
  # END

  def index
    @articles = Article.all
  end

  # BEGIN
  def show
    @article = Article.find(params[:id])
  end
  # END
end

rails-full-ru/caching/app/controllers/web/home_controller.rb
# frozen_string_literal: true

class Web::HomeController < Web::ApplicationController
  def index; end
end

rails-full-ru/caching/app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

rails-full-ru/caching/app/views/web/articles/_article.html.slim
.col.mb-3
  .card.h-100
    .card-body
      h5.card-title
        = link_to article.title, article_path(article.id)
      h6.card-subtitle.mb-2.text-muted
        = l article.published_at, format: :short
      .card-text.mb-2
        = article.summary

        .small.text-muted
          = l article.last_reading_date, foramt: :short

rails-full-ru/caching/app/views/web/articles/index.html.slim
= content_for :title do
  = t('.articles')

.row.row-cols-3
  - @articles.each do |article|
    / BEGIN
    - cache article do
      = render article
    / END

rails-full-ru/caching/app/views/web/articles/show.html.slim
= content_for :title do
  = @article.title

.row.row-cols-3
  = @article.body