rails-real-ru/fsm/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :vacancies, only: %i[index new create] do
    # BEGIN
    member do
      patch 'publish'
      patch 'archive'
    end
    # END
  end

  root 'vacancies#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

rails-real-ru/fsm/app/models/vacancy.rb
# frozen_string_literal: true

class Vacancy < ApplicationRecord
  include AASM

  validates :title, presence: true
  validates :description, presence: true

  # BEGIN
  aasm whiny_transitions: false do
    state :on_moderate, initial: true
    state :published
    state :archived

    event :publish do
      transitions from: :on_moderate, to: :published
    end

    event :archive do
      transitions from: %i[on_moderate published], to: :archived
    end
  end
  # END
end

rails-real-ru/fsm/app/controllers/vacancies_controller.rb
# frozen_string_literal: true

class VacanciesController < ApplicationController
  before_action :set_vacancy, only: %i[publish archive]

  def index
    @on_moderate = Vacancy.on_moderate
    @published = Vacancy.published
  end

  def new
    @vacancy = Vacancy.new
  end

  def create
    @vacancy = Vacancy.new(vacancy_params)

    if @vacancy.save
      redirect_to vacancies_path, notice: 'Vacancy was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  # BEGIN
  def publish
    @vacancy.publish
    if @vacancy.save
      redirect_to vacancies_path, notice: 'Vacancy was successfully published'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def archive
    @vacancy.archive
    if @vacancy.save
      redirect_to vacancies_path, notice: 'Vacancy was successfully archived'
    else
      render :new, status: :unprocessable_entity
    end
  end
  # END

  private

  def vacancy_params
    params.require(:vacancy).permit(:title, :description)
  end

  def set_vacancy
    @vacancy = Vacancy.find(params[:id])
  end
end

rails-real-ru/fsm/app/helpers/vacancies_helper.rb
# frozen_string_literal: true

module VacanciesHelper
end

rails-real-ru/fsm/app/views/vacancies/_form.html.slim
= simple_form_for(vacancy) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  = f.input :title, input_html: { class: 'form-control' }, label_html: { class: 'form-label' }
  = f.input :description, input_html: { class: 'form-control' }, label_html: { class: 'form-label' }

  = f.button :submit, class: 'btn btn-success mt-4 btn-block'

rails-real-ru/fsm/app/views/vacancies/index.html.slim
= content_for :title do
  = 'Vacancies'

h2 On moderate

table.table.table-striped.table-hover.mb-5
  thead
    tr
      th Title
      th Description
      th Action

  tbody
    - @on_moderate.each do |vacancy|
      tr
        td = vacancy.title
        td = vacancy.description
        td.d-flex
          / BEGIN
          = link_to 'Publish', publish_vacancy_path(vacancy), method: :patch
          = link_to 'Archive', archive_vacancy_path(vacancy), method: :patch
          / END

h2 Published

table.table.table-striped.table-hover.mb-5
  thead
    tr
      th Title
      th Description
      th Action

  tbody
    - @published.each do |vacancy|
      tr
        td = vacancy.title
        td = vacancy.description
        td.d-flex
          .me-4 = link_to 'Archive', archive_vacancy_path(vacancy), method: :patch

= link_to 'New Vacancy', new_vacancy_path, class: 'btn btn-primary'

rails-real-ru/fsm/app/views/vacancies/new.html.slim
= content_for :title do
  = 'New vacancy'

== render 'form', vacancy: @vacancy

hr

= link_to 'Back', :back, class: 'btn btn-outline-primary'